In [3]:
from datetime import datetime, timedelta
import time
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import pandas as pd

## Loading the data

In [13]:
# geomagnetic and solar indices
df_geom = pd.read_csv("data/geomagnetic-solarindices.txt", sep=r"\s+",header=None)
df_geom.head()

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,2010,1,1,28490,28490.5,2407,15,0.000,0.000,0.000,...,0,0,0,0,4,0,18,75.2,72.7,2
1,2010,1,2,28491,28491.5,2407,16,0.000,0.000,0.333,...,2,0,2,2,2,1,21,78.0,75.4,2
2,2010,1,3,28492,28492.5,2407,17,0.333,1.333,0.667,...,7,6,3,0,2,4,16,76.4,73.8,2
3,2010,1,4,28493,28493.5,2407,18,0.333,0.000,1.333,...,4,2,0,2,0,2,15,73.0,70.6,2
4,2010,1,5,28494,28494.5,2407,19,0.000,0.000,0.000,...,0,3,4,2,0,1,10,76.8,74.3,2

In [34]:
df_kp = df_geom[[7,8,9,10,11,12,13,14]]
df_kp.head() # index means days from 2010-01-01

      7      8      9      10     11     12     13     14
0  0.000  0.000  0.000  0.000  0.000  0.000  0.000  1.000
1  0.000  0.000  0.333  0.333  0.000  0.333  0.333  0.333
2  0.333  1.333  0.667  2.000  1.667  0.667  0.000  0.333
3  0.333  0.000  1.333  1.000  0.333  0.000  0.333  0.000
4  0.000  0.000  0.000  0.000  0.667  1.000  0.333  0.000

In [30]:
df_kp = pd.DataFrame()
tindex =
for r in df_kp.values:#.loc[:3,[0,1,2]].values:
    
    print(i)

[2.01e+03 1.00e+00 1.00e+00 1.50e+01 0.00e+00 0.00e+00 0.00e+00 0.00e+00
 0.00e+00 0.00e+00 0.00e+00 1.00e+00]